# Generated by Django 5.0.14 on 2025-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Пользователь', max_length=150, verbose_name='Фамилия'),
        ),
    ]
