# Generated by Django 5.0.14 on 2025-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0007_person_creator'),
        ('gallery', '0007_album_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('repeat', models.CharField(choices=[('none', 'Не повторяется'), ('yearly', 'Каждый год'), ('custom', 'Каждые N лет')], default='none', max_length=25, verbose_name='Повтор')),
                ('event_type', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('anniversary', 'Юбилей'), ('memory', 'Памятное событие'), ('military', 'Армия / фронт'), ('death', 'Смерть'), ('study', 'Учёба / работа'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_reminder_enabled', models.BooleanField(default=False, verbose_name='Напоминание включено')),
                ('is_in_timeline', models.BooleanField(default=True, verbose_name='Показывать в хронологии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='gallery.category', verbose_name='Категории')),
                ('people', models.ManyToManyField(blank=True, null=True, related_name='events', to='family_tree.person', verbose_name='Связанные лица')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('date',),
            },
        ),
    ]
