# Generated by Django 5.0.14 on 2025-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('family_tree', '0013_alter_person_photo_other'),
        ('gallery', '0010_album_views_albumlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, to='gallery.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='events', to='family_tree.person', verbose_name='Связанные лица'),
        ),
    ]
