# Generated by Django 5.0.14 on 2025-07-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_owner'),
        ('gallery', '0010_album_views_albumlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='gallery.album', verbose_name='Альбом события'),
        ),
    ]
