# Generated by Django 5.0.14 on 2025-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_one',
            field=models.ImageField(blank=True, null=True, upload_to='event_photo/', verbose_name='Фото для события 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_two',
            field=models.ImageField(blank=True, null=True, upload_to='event_photo/', verbose_name='Фото для события 2'),
        ),
    ]
