# Generated by Django 5.0.14 on 2025-06-10 07:16

import django.db.models.deletion
import gallery.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0007_person_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание альбома')),
                ('cover_image', models.ImageField(upload_to='album_covers/', verbose_name='Обложка альбома')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='gallery.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.utils.photo_upload_path, verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album', verbose_name='Привязка к альбому')),
                ('people', models.ManyToManyField(blank=True, null=True, related_name='photos', to='family_tree.person', verbose_name='Привязка к карточке')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='photos', to='gallery.tag', verbose_name='Привязка к тегам')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=gallery.utils.video_upload_path, verbose_name='Видео')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.album', verbose_name='Привязка к альбому')),
                ('people', models.ManyToManyField(blank=True, null=True, related_name='videos', to='family_tree.person', verbose_name='Привязка к карточке')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='videos', to='gallery.tag', verbose_name='Привязка к тегам')),
            ],
        ),
    ]
