# Generated by Django 5.0.14 on 2025-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_location_alter_photo_people_alter_photo_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='albums', to='gallery.tag', verbose_name='Теги'),
        ),
    ]
