# Generated by Django 5.0.14 on 2025-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность альбома'),
        ),
    ]
