# Generated by Django 5.0.14 on 2025-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0011_alter_person_slug'),
        ('gallery', '0008_album_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='photos', to='family_tree.person', verbose_name='Привязка к карточке'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='gallery.tag', verbose_name='Привязка к тегам'),
        ),
        migrations.AlterField(
            model_name='video',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='videos', to='family_tree.person', verbose_name='Привязка к карточке'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='gallery.tag', verbose_name='Привязка к тегам'),
        ),
    ]
