# Generated by Django 5.0.14 on 2025-07-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_albumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Редактирование комментария'),
        ),
    ]
