# Generated by Django 5.0.14 on 2025-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_albumcomment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
