# Generated by Django 5.0.14 on 2025-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patronymic')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Death Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('profession', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession')),
                ('favorite_food', models.CharField(blank=True, max_length=150, null=True)),
                ('playlist', models.URLField(blank=True, null=True, verbose_name='music')),
                ('hobbies', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hobby')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
