# Generated by Django 5.0.14 on 2025-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maiden Name'),
        ),
    ]
