# Generated by Django 5.0.14 on 2025-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_alter_person_options_alter_person_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/', verbose_name='Фотография'),
        ),
    ]
