# Generated by Django 5.0.14 on 2025-06-07 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0006_alter_person_father_alter_person_mother_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL, verbose_name='Создатель карточки'),
        ),
    ]
