# Generated by Django 5.0.14 on 2025-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0010_auto_20250628_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
