# Generated by Django 5.0.14 on 2025-06-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0011_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_other',
            field=models.ImageField(blank=True, null=True, upload_to='person_other_photos/', verbose_name='Фотография'),
        ),
    ]
