# Generated by Django 5.0.14 on 2025-06-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0012_person_photo_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo_other',
            field=models.ImageField(blank=True, null=True, upload_to='person_other_photos/', verbose_name='Фотография_2'),
        ),
    ]
