# Generated by Django 5.0.14 on 2025-07-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0013_alter_person_photo_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
