# Generated by Django 5.0.14 on 2025-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0014_person_birth_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения'),
        ),
    ]
